name: CD

on:
  push:
    branches: [ master ]

jobs:
  do_contact_store:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_IP }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_PK }}
          script: |
            cd ${{ secrets.DO_ROOT }}
            eval "$(ssh-agent -s)"
            ssh-add ../.ssh/contact_store
            git reset --hard
            git pull
            cd web
            yarn install
            yarn production
            cd ..
            /usr/local/go/bin/go build -o contact_store cmd/web/*.go
            chmod +x contact_store
            supervisorctl restart contact_store